# Starter pipeline

trigger:
- main

pool:
  Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UiPathInstallPlatform@6
  inputs:
    cliVersion: 'Windows.25.10.3'

- task: UiPathPack@6
  inputs:
    projectJsonPath: '$(Build.SourcesDirectory)'
    versionType: 'AutoVersion'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    orchestratorConnection: 'azure'

- task: UiPathDeploy@6
  inputs:
      orchestratorConnection: 'azure'
      packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
      folderName: 'din'
      environments: 'prod'


